# Generated by Django 3.1.1 on 2021-05-08 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'article")),
                ('description', models.TextField()),
                ('price_init', models.IntegerField(null=True, verbose_name='Prix initial')),
                ('price_ttc', models.IntegerField(null=True, verbose_name='Prix TTC')),
                ('number', models.IntegerField(default=1, verbose_name="Nombre d'article dispo")),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('district', models.CharField(max_length=100, verbose_name='Quartier')),
                ('seen', models.IntegerField(default=0, verbose_name='Nombre de vue')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté')),
                ('date_edit', models.DateTimeField(null=True, verbose_name='Modifié')),
                ('image_min', models.ImageField(null=True, upload_to=store.models.pictures_rename)),
                ('img_background', models.CharField(max_length=100, null=True)),
                ('delivery', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-date_add'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Etat',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Villes',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to=store.models.pictures_rename)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.article')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Etat')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='store.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favoris',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='Categorie'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.status', verbose_name='Etat'),
        ),
        migrations.AddField(
            model_name='article',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.town', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
