# Generated by Django 3.1.1 on 2021-05-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210519_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='articles',
            field=models.ManyToManyField(related_name='favourite', to='store.Article'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='store.article'),
        ),
    ]
