# Generated by Django 3.1.1 on 2020-10-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_delete_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name': 'Favoris'},
        ),
        migrations.AddField(
            model_name='favourite',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default='2020-10-12 10:53:32', verbose_name="Date d'ajout"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_edit',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Modifié'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
    ]
