# Generated by Django 3.1.1 on 2020-10-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201012_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_add'], 'verbose_name': 'Article'},
        ),
        migrations.AddField(
            model_name='article',
            name='image_min',
            field=models.ImageField(null=True, upload_to='article_img/'),
        ),
    ]
