# Generated by Django 3.1.1 on 2020-10-26 14:01

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201012_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='delivery',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_edit',
            field=models.DateTimeField(verbose_name='Modifié'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_min',
            field=models.ImageField(null=True, upload_to=store.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(null=True, upload_to=store.models.pictures_rename),
        ),
    ]
