# Generated by Django 3.1.1 on 2020-10-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201026_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_edit',
            field=models.DateTimeField(null=True, verbose_name='Modifié'),
        ),
    ]
