# Generated by Django 3.1.1 on 2020-12-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201117_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price_init',
            field=models.IntegerField(null=True, verbose_name='Prix initial'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price_ttc',
            field=models.IntegerField(null=True, verbose_name='Prix TTC'),
        ),
    ]
