# Generated by Django 3.1.1 on 2020-12-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201201_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_min',
            field=models.ImageField(null=True, upload_to='article_img'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(null=True, upload_to='article_img'),
        ),
    ]
