# Generated by Django 3.1.1 on 2020-12-02 17:40

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201202_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_min',
            field=models.ImageField(null=True, upload_to=store.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(null=True, upload_to=store.models.pictures_rename),
        ),
    ]
