# Generated by Django 3.1.1 on 2020-12-11 17:12

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201202_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_min',
            field=models.ImageField(null=True, upload_to=store.models.pictures_rename),
        ),
    ]
