# Generated by Django 3.1.1 on 2020-12-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201211_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_background',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
