# Generated by Django 3.1.1 on 2021-06-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='airtel_account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mtn_account_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
