# Generated by Django 3.1.1 on 2021-07-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210703_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='airtel_account_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mtn_account_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
