# Generated by Django 3.1.1 on 2021-06-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210608_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='mtn_account_number',
            field=models.CharField(max_length=20),
        ),
    ]
