# Generated by Django 3.1.1 on 2020-10-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201028_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
