# Generated by Django 3.1.1 on 2020-10-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manage',
            field=models.BooleanField(default=False),
        ),
    ]
