# Generated by Django 3.1.1 on 2020-10-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20201027_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_t_ht',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_t_ttc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_u_ht',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_u_ttc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
