# Generated by Django 3.1.1 on 2020-10-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20201031_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_t_ht',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_t_ttc',
        ),
    ]
