# Generated by Django 3.1.1 on 2020-10-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20201031_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price_u_ht',
            new_name='price_ht',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='price_u_ttc',
            new_name='price_ttc',
        ),
    ]
