# Generated by Django 3.1.1 on 2020-11-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_order_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='expired',
            new_name='manage',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date_expired',
        ),
    ]
