# Generated by Django 3.1.1 on 2020-11-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20201101_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=100)),
                ('price_ttc', models.IntegerField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('archive_type', models.CharField(max_length=100)),
            ],
        ),
    ]
