# Generated by Django 3.1.1 on 2020-10-11 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type_msg', models.CharField(max_length=20)),
                ('date_send', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoie")),
                ('readed', models.BooleanField(default=False)),
                ('sender', models.ManyToManyField(related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
        ),
    ]
