# Generated by Django 3.1.1 on 2021-07-01 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210706_1628'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('delivred', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotifMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('delivred', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterModelOptions(
            name='talk',
            options={},
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='last_message_date',
            new_name='date_create',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='user1_id',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='user2_id',
        ),
        migrations.AddField(
            model_name='talk',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='store.article'),
        ),
        migrations.AddField(
            model_name='talk',
            name='users',
            field=models.ManyToManyField(related_name='talks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MessageText',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='communication.talk'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
