# Generated by Django 3.1.1 on 2020-10-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_auto_20201011_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
