# Generated by Django 3.1.1 on 2020-10-12 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0003_message_sender_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='recipient_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='users',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
    ]
