# Generated by Django 3.1.1 on 2021-07-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_auto_20210701_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='users',
        ),
        migrations.AddField(
            model_name='talk',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='seller_id',
            field=models.IntegerField(null=True),
        ),
    ]
