# Generated by Django 3.1.1 on 2021-07-02 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_auto_20210702_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='customer_id',
            new_name='user_one',
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='seller_id',
            new_name='user_two',
        ),
    ]
