# Generated by Django 3.1.1 on 2020-11-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_auto_20201011_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient_id',
            field=models.IntegerField(verbose_name='Recevreur'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type_msg',
            field=models.CharField(choices=[('message', 'Message')], default='notif', max_length=100),
        ),
    ]
