# Generated by Django 3.1.1 on 2020-11-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_auto_20201101_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
