# Generated by Django 3.1.1 on 2020-11-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_message_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-date_send',), 'verbose_name': 'Message'},
        ),
    ]
