# Generated by Django 3.1.1 on 2020-11-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_auto_20201107_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='users',
        ),
        migrations.AddField(
            model_name='talk',
            name='user1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talk',
            name='user2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
