# Generated by Django 3.1.1 on 2020-11-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0009_auto_20201111_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'verbose_name': 'Conversation'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Talk',
            new_name='talk',
        ),
    ]
