# Generated by Django 3.1.1 on 2020-11-11 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_invoice'),
        ('communication', '0010_auto_20201111_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.article'),
        ),
    ]
