# Generated by Django 3.1.1 on 2020-11-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_auto_20201112_0630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talk',
        ),
    ]
