# Generated by Django 3.1.1 on 2020-11-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0014_messagetext_talk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='artitcle',
            new_name='article',
        ),
    ]
