# Generated by Django 3.1.1 on 2020-11-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0015_auto_20201112_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetext',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
