# Generated by Django 3.1.1 on 2020-11-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0016_messagetext_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetext',
            options={'ordering': ('-date',), 'verbose_name': 'Message texte'},
        ),
        migrations.AlterModelOptions(
            name='talk',
            options={'verbose_name': 'Conversation'},
        ),
        migrations.AddField(
            model_name='messagetext',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
