# Generated by Django 3.1.1 on 2020-11-13 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0017_auto_20201112_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={},
        ),
        migrations.RemoveField(
            model_name='messagetext',
            name='recipient_id',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='article',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='users',
        ),
        migrations.AddField(
            model_name='messagetext',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagetext',
            name='talk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='communication.talk'),
        ),
    ]
