# Generated by Django 3.1.1 on 2020-11-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0018_auto_20201113_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='user1_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talk',
            name='user2_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
