# Generated by Django 3.1.1 on 2020-11-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0019_auto_20201113_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ('-last_message_date',), 'verbose_name': 'Conversation'},
        ),
        migrations.AddField(
            model_name='talk',
            name='last_message_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
