# Generated by Django 3.1.1 on 2020-11-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0020_auto_20201113_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetext',
            options={'ordering': ('date',), 'verbose_name': 'Message texte'},
        ),
        migrations.AddField(
            model_name='messagetext',
            name='alert_play',
            field=models.BooleanField(default=False),
        ),
    ]
