# Generated by Django 3.1.1 on 2021-07-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='mobile_money',
        ),
        migrations.AddField(
            model_name='profil',
            name='airtel_money',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='contact_airtel',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='contact_mtn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='mtn_money',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='whatsap_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
