# Generated by Django 3.1.1 on 2020-12-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201011_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='mobile_money',
            field=models.IntegerField(null=True),
        ),
    ]
