# Generated by Django 3.1.1 on 2021-07-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210702_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.gender'),
        ),
    ]
