# Generated by Django 3.1.1 on 2021-07-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210702_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='airtel_money',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='contact_airtel',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='mtn_money',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='whatsap_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
